### ISSUE TITLE
代码里面为什么好多没用值？而且指数平移算法存在问题？

### ISSUE THREAD

**Issue by guozhuoyuan** [MezereonXP/AnomalyDetectTool#32]
大佬，为什么我用你的HoltWintersTool时，只要数值过大，或者精度太小，alpha全都变为NaN。T^T。

**Comment by guozhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/34533751/43507694-6b923ffc-95a0-11e8-8a00-2af6f32bc9de.png)

**Comment by guozhuoyuan** [comment]
大佬们，你们应该要把剔除的值保留起来，而不是一味的扔掉。

**Comment by MezereonXP** [comment]
这个应该是梯度下降的时候出现了问题, 很有可能是梯度过大, 解决方案是对数据进行归一化或者标准化, 将会在后续进行修复

**Comment by guozhuoyuan** [comment]
能加个微信交流一下吗？

**Comment by MezereonXP** [comment]
可以啊, 你加我微信吧, saberxp47
